Repository CommunitySolidServer/CommunitySolidServer, pull requests merged in 2020-09, with the labels that each got.

#115 Send server identification
  src/server/ExpressHttpServer.ts
  test/unit/server/ExpressHttpServer.test.ts
Labels: feature ➕

#118 Support all PUT operations, error later
  src/ldp/operations/PutOperationHandler.ts
  test/unit/ldp/operations/PutOperationHandler.test.ts
Labels: bug 🐛

#123 Determine body presence according to RFC7230
  src/ldp/http/RawBodyParser.ts
  test/integration/AuthenticatedLdpHandler.test.ts
  test/integration/Authorization.test.ts
  test/integration/RequestParser.test.ts
  test/unit/ldp/http/RawBodyParser.test.ts
Labels: bug 🐛

#129 Add package metadata
  package.json
Labels: documentation 📚

#130 fix: Don't buffer data before sending response with InMemoryResourceStore
  src/storage/InMemoryResourceStore.ts
  test/unit/storage/InMemoryResourceStore.test.ts
Labels: bug 🐛

#131 Add context to README
  README.md
Labels: documentation 📚

#134 Make deployment test install packages
  .travis/validate-package.sh
Labels: bug 🐛

#152 refactor: Make URI constants consistent
  .eslintrc.js
  src/authorization/AclConstants.ts
  src/authorization/WebAclAuthorizer.ts
  src/init/Setup.ts
  src/ldp/http/RawBodyParser.ts
  src/ldp/http/SparqlUpdateBodyParser.ts
  src/ldp/representation/MetadataUtil.ts
  src/ldp/representation/RepresentationMetadata.ts
  src/storage/FileResourceStore.ts
  src/storage/InMemoryResourceStore.ts
  src/storage/conversion/ChainedConverter.ts
  src/storage/conversion/QuadToRdfConverter.ts
  src/storage/conversion/QuadToTurtleConverter.ts
  src/storage/conversion/RdfToQuadConverter.ts
  src/storage/conversion/TurtleToQuadConverter.ts
  src/storage/patch/SparqlUpdatePatchHandler.ts
  src/util/InteractionController.ts
  src/util/LinkTypes.ts
  src/util/MetadataController.ts
  src/util/MetadataTypes.ts
  src/util/Prefixes.ts
  src/util/UriConstants.ts
  src/util/UriUtil.ts
  test/integration/FileResourceStore.test.ts
  test/integration/RepresentationConverter.test.ts
  test/unit/ldp/http/BasicResponseWriter.test.ts
  test/unit/ldp/http/RawBodyParser.test.ts
  test/unit/ldp/representation/RepresentationMetadata.test.ts
  test/unit/storage/FileResourceStore.test.ts
  test/unit/storage/RepresentationConvertingStore.test.ts
  test/unit/storage/conversion/ChainedConverter.test.ts
  test/unit/storage/conversion/QuadToRdfConverter.test.ts
  test/unit/storage/conversion/QuadToTurtleConverter.test.ts
  test/unit/storage/conversion/RdfToQuadConverter.test.ts
  test/unit/storage/conversion/TurtleToQuadConverter.test.ts
  test/unit/util/UriUtil.test.ts
  test/util/TestHelpers.ts
Labels: enhancement ☀️
