Repository CommunitySolidServer/CommunitySolidServer, pull requests merged in 2020-11, with the labels that each got.

#293 Update all dependencies
  .eslintrc.js
  package-lock.json
  src/ldp/representation/RepresentationMetadata.ts
  src/logging/WinstonLoggerFactory.ts
  src/storage/DataAccessorBasedStore.ts
  src/storage/accessors/InMemoryDataAccessor.ts
  src/storage/conversion/ChainedConverter.ts
  src/storage/conversion/QuadToRdfConverter.ts
  src/storage/conversion/RdfToQuadConverter.ts
  src/storage/conversion/TypedRepresentationConverter.ts
  src/util/HeaderUtil.ts
  src/util/UriUtil.ts
  test/unit/storage/DataAccessorBasedStore.test.ts
  test/unit/storage/ExtensionBasedMapper.test.ts
  test/unit/storage/conversion/ChainedConverter.test.ts
Labels: 📝 task

#290 Use Jest recommended linting
  .eslintrc.js
  package-lock.json
  package.json
  test/.eslintrc.js
  test/unit/init/CliRunner.test.ts
  test/unit/ldp/http/BasicResponseWriter.test.ts
  test/unit/ldp/http/metadata/BasicMetadataExtractor.test.ts
  test/unit/logging/LogUtil.test.ts
  test/unit/server/ExpressHttpServer.test.ts
  test/unit/storage/LockingResourceStore.test.ts
  test/unit/storage/SingleThreadedResourceLocker.test.ts
  test/unit/storage/accessors/FileDataAccessor.test.ts
  test/unit/storage/patch/SparqlUpdatePatchHandler.test.ts
  test/util/TestHelpers.ts
Labels: 📝 task

#335 feat: Add a monitoring store
  src/storage/MonitoringStore.ts
  test/unit/storage/MonitoringStore.test.ts
Labels: ➕ feature

#342 Add ExpressHttpServerFactory
  config/presets/http.json
  config/presets/setup.json
  index.ts
  src/init/Setup.ts
  src/server/ExpressHttpServerFactory.ts
  src/server/HttpServerFactory.ts
  test/unit/init/Setup.test.ts
  test/unit/server/ExpressHttpServerFactory.test.ts
Labels: 📝 task

#336 Add WebSocket functionality to server
  .eslintrc.js
  package-lock.json
  package.json
  src/server/WebSocketHandler.ts
  src/server/WebSocketServerFactory.ts
  test/.eslintrc.js
  test/unit/server/WebSocketServerFactory.test.ts
Labels: ➕ feature

#339 Add the legacy Solid WebSocket protocol
  .eslintrc.js
  src/ldp/UnsecureWebSocketsProtocol.ts
  test/unit/ldp/UnsecureWebSocketsProtocol.test.ts
Labels: ⌛ has dependency, ➕ feature

#351 Set up GitHub Actions
  .github/workflows/ci.yml
  .travis.yml
Labels: 📝 task

#356 fix: Update quad converter config parameters
  config/presets/storage/backend/storage-sparql-endpoint.json
Labels: 🐛 bug

#357 Add WebSockets integration test
  package-lock.json
  package.json
  test/configs/Util.ts
  test/configs/websockets.json
  test/integration/WebSocketsProtocol.test.ts
Labels: ➕ test

#359 Drop Node 10 support
  .github/workflows/ci.yml
  src/ldp/http/SparqlUpdateBodyParser.ts
  src/storage/conversion/RdfToQuadConverter.ts
  test/unit/ldp/http/SparqlUpdateBodyParser.test.ts
Labels: 📝 task

#362 Rename UnsupportedHttpError into BadRequestError
  index.ts
  src/ldp/http/BasicResponseWriter.ts
  src/ldp/http/ErrorResponseWriter.ts
  src/ldp/http/RawBodyParser.ts
  src/ldp/http/SparqlUpdateBodyParser.ts
  src/ldp/http/metadata/SlugParser.ts
  src/ldp/operations/DeleteOperationHandler.ts
  src/ldp/operations/GetOperationHandler.ts
  src/ldp/operations/HeadOperationHandler.ts
  src/ldp/operations/PatchOperationHandler.ts
  src/ldp/operations/PostOperationHandler.ts
  src/ldp/operations/PutOperationHandler.ts
  src/ldp/permissions/MethodPermissionsExtractor.ts
  src/ldp/permissions/SparqlPatchPermissionsExtractor.ts
  src/storage/DataAccessorBasedStore.ts
  src/storage/RoutingResourceStore.ts
  src/storage/accessors/DataAccessor.ts
  src/storage/accessors/SparqlDataAccessor.ts
  src/storage/conversion/ConversionUtil.ts
  src/storage/conversion/RdfToQuadConverter.ts
  src/storage/mapping/ExtensionBasedMapper.ts
  src/storage/mapping/FixedContentTypeMapper.ts
  src/storage/mapping/MapperUtil.ts
  src/storage/patch/SparqlUpdatePatchHandler.ts
  src/storage/routing/RegexRouterRule.ts
  src/util/FirstCompositeHandler.ts
  src/util/HeaderUtil.ts
  src/util/errors/BadRequestHttpError.ts
  src/util/errors/NotImplementedHttpError.ts
  test/unit/ldp/http/BasicResponseWriter.test.ts
  test/unit/ldp/http/ErrorResponseWriter.test.ts
  test/unit/ldp/http/SparqlUpdateBodyParser.test.ts
  test/unit/ldp/http/metadata/SlugParser.test.ts
  test/unit/ldp/operations/DeleteOperationHandler.test.ts
  test/unit/ldp/operations/GetOperationHandler.test.ts
  test/unit/ldp/operations/HeadOperationHandler.test.ts
  test/unit/ldp/operations/PatchOperationHandler.test.ts
  test/unit/ldp/operations/PostOperationHandler.test.ts
  test/unit/ldp/operations/PutOperationHandler.test.ts
  test/unit/ldp/permissions/BasePermissionsExtractor.test.ts
  test/unit/ldp/permissions/SparqlPatchPermissionsExtractor.test.ts
  test/unit/storage/DataAccessorBasedStore.test.ts
  test/unit/storage/RoutingResourceStore.test.ts
  test/unit/storage/accessors/SparqlDataAccessor.test.ts
  test/unit/storage/conversion/ConversionUtil.test.ts
  test/unit/storage/conversion/RdfToQuadConverter.test.ts
  test/unit/storage/mapping/ExtensionBasedMapper.test.ts
  test/unit/storage/mapping/FixedContentTypeMapper.test.ts
  test/unit/storage/patch/SparqlUpdatePatchHandler.test.ts
  test/unit/storage/routing/PreferenceSupport.test.ts
  test/unit/storage/routing/RegexRouterRule.test.ts
  test/unit/util/FirstCompositeHandler.test.ts
  test/unit/util/errors/BadRequestHttpError.test.ts
Labels: 🐛 bug
