Repository CommunitySolidServer/CommunitySolidServer, pull requests merged in 2020-10, with the labels that each got.

#171 build: Add eslint cache
  .gitignore
  package.json
Labels: performance 🐌

#170 fix: Retain status codes when combining errors
  src/util/CompositeAsyncHandler.ts
  src/util/errors/HttpError.ts
  src/util/errors/InternalServerError.ts
  test/unit/util/CompositeAsyncHandler.test.ts
Labels: bug 🐛

#269 fix: Remove metadata file if no new metadata is stored
  src/storage/accessors/FileDataAccessor.ts
  test/unit/storage/accessors/FileDataAccessor.test.ts
Labels: 🐛 bug

#289 Implement empty canHandle on base class
  src/authentication/UnsecureWebIdExtractor.ts
  src/authorization/AllowEverythingAuthorizer.ts
  src/authorization/WebAclAuthorizer.ts
  src/ldp/http/AcceptPreferenceParser.ts
  src/ldp/http/BasicRequestParser.ts
  src/ldp/http/BasicTargetExtractor.ts
  src/ldp/http/RawBodyParser.ts
  src/ldp/http/metadata/BasicMetadataExtractor.ts
  src/util/AsyncHandler.ts
  test/unit/authentication/UnsecureWebIdExtractor.ts
  test/unit/authorization/AllowEverythingAuthorizer.test.ts
  test/unit/authorization/WebAclAuthorizer.test.ts
  test/unit/ldp/http/AcceptPreferenceParser.test.ts
  test/unit/ldp/http/BasicRequestParser.test.ts
  test/unit/ldp/http/BasicTargetExtractor.test.ts
  test/unit/ldp/http/RawBodyParser.test.ts
  test/unit/ldp/http/metadata/BasicMetadataExtractor.test.ts
  test/unit/server/ExpressHttpServer.test.ts
  test/unit/util/AsyncHandler.test.ts
Labels: 📝 task

#292 Organize tests
  .travis.yml
  package-lock.json
  package.json
  test/deploy/validate-package.sh
Labels: ➕ test
