Repository CommunitySolidServer/CommunitySolidServer, pull requests merged in 2020-12, with the labels that each got.

#375 fix: Always release lock when patching
  src/storage/patch/SparqlUpdatePatchHandler.ts
  test/unit/storage/patch/SparqlUpdatePatchHandler.test.ts
Labels: 🐛 bug

#377 Support the Forwarded header
  src/ldp/UnsecureWebSocketsProtocol.ts
  src/ldp/http/BasicTargetExtractor.ts
  src/util/HeaderUtil.ts
  test/integration/WebSocketsProtocol.test.ts
  test/unit/ldp/UnsecureWebSocketsProtocol.test.ts
  test/unit/ldp/http/BasicTargetExtractor.test.ts
  test/unit/util/HeaderUtil.test.ts
Labels: ➕ feature

#390 Do not overwrite existing root ACL
  src/init/Setup.ts
  test/unit/init/Setup.test.ts
Labels: 🐛 bug

#405 test: Use separate linter job
  .github/workflows/ci.yml
Labels: ➕ test

#401 Add read-only store
  index.ts
  src/storage/ReadOnlyStore.ts
  test/unit/storage/ReadOnlyStore.test.ts
Labels: ➕ feature

#416 Make RepresentationMetadata accept a ResourceIdentifier
  src/init/AclInitializer.ts
  src/ldp/representation/RepresentationMetadata.ts
  src/ldp/representation/ResourceIdentifier.ts
  src/pods/generate/TemplatedResourcesGenerator.ts
  src/storage/DataAccessorBasedStore.ts
  src/storage/accessors/FileDataAccessor.ts
  src/storage/accessors/InMemoryDataAccessor.ts
  src/storage/accessors/SparqlDataAccessor.ts
  src/storage/patch/SparqlUpdatePatchHandler.ts
  test/unit/ldp/representation/RepresentationMetadata.test.ts
  test/unit/storage/accessors/FileDataAccessor.test.ts
  test/unit/storage/accessors/InMemoryDataAccessor.test.ts
  test/unit/storage/accessors/SparqlDataAccessor.test.ts
Labels: 📝 task

#431 Add constant WebID extractor
  src/authentication/UnsecureConstantCredentialsExtractor.ts
  test/unit/authentication/UnsecureConstantCredentialsExtractor.test.ts
Labels: ➕ feature, 👩🏾‍💻 developer experience

#429 fix: Make default HttpHandler a WaterfallHandler
  config/presets/http.json
  test/integration/Middleware.test.ts
Labels: 🐛 bug
