Repository CommunitySolidServer/CommunitySolidServer, pull requests merged in 2021-02, with the labels that each got.

#601 refactor: upgraded @types/cors
  package-lock.json
  package.json
  src/server/middleware/CorsHandler.ts
Labels: ⚙️ dependencies

#604 Replace express with native http module
  config/presets/http.json
  package-lock.json
  package.json
  src/index.ts
  src/server/BaseHttpServerFactory.ts
  src/server/ExpressHttpServerFactory.ts
  test/integration/Middleware.test.ts
  test/unit/server/BaseHttpServerFactory.test.ts
  test/unit/server/WebSocketServerFactory.test.ts
Labels: ☀️ enhancement

#620 feat/correctly-handle-slug-in-POST-request
  src/storage/DataAccessorBasedStore.ts
  test/integration/LdpHandlerWithAuth.test.ts
  test/integration/LdpHandlerWithoutAuth.test.ts
  test/integration/SparqlStorage.test.ts
  test/unit/storage/DataAccessorBasedStore.test.ts
  test/util/TestHelpers.ts
Labels: 🐛 bug

#633 feat: added resourceExists method to ResourceStore
  jest.config.js
  src/init/AclInitializer.ts
  src/init/RootContainerInitializer.ts
  src/pods/GeneratedPodManager.ts
  src/storage/BaseResourceStore.ts
  src/storage/DataAccessorBasedStore.ts
  src/storage/LockingResourceStore.ts
  src/storage/MonitoringStore.ts
  src/storage/PassthroughStore.ts
  src/storage/ResourceStore.ts
  src/storage/RoutingResourceStore.ts
  src/storage/StoreUtil.ts
  src/storage/routing/ConvertingRouterRule.ts
  test/integration/LdpHandlerWithAuth.test.ts
  test/unit/init/AclInitializer.test.ts
  test/unit/init/RootContainerInitializer.test.ts
  test/unit/pods/GeneratedPodManager.test.ts
  test/unit/storage/BaseResourceStore.test.ts
  test/unit/storage/DataAccessorBasedStore.test.ts
  test/unit/storage/LockingResourceStore.test.ts
  test/unit/storage/MonitoringStore.test.ts
  test/unit/storage/PassthroughStore.test.ts
  test/unit/storage/RoutingResourceStore.test.ts
  test/unit/storage/routing/ConvertingRouterRule.test.ts
Labels: ➕ feature
