Repository CommunitySolidServer/CommunitySolidServer, pull requests merged in 2021-04, with the labels that each got.

#662 feat: redis based locking mechanism
  .github/workflows/ci.yml
  package-lock.json
  package.json
  src/index.ts
  src/util/locking/RedisResourceLocker.ts
  test/integration/RedisResourceLockerIntegration.test.ts
  test/integration/config/run-with-redlock.json
  test/unit/util/locking/RedisResourceLocker.test.ts
Labels: ➕ feature

#706 Improve identifier error messages
  src/util/identifiers/BaseIdentifierStrategy.ts
  test/unit/util/identifiers/BaseIdentifierStrategy.test.ts
Labels: 📚 documentation

#707 Test on Node 16
  .github/workflows/ci.yml
Labels: ➕ test
