Repository CommunitySolidServer/CommunitySolidServer, pull requests merged in 2021-11, with the labels that each got.

#1037 Run integration tests separately
  .github/workflows/ci.yml
Labels: ➕ test

#1035 Do not serve UI on special pages
  config/ldp/handler/components/error-handler.json
  config/storage/middleware/stores/converting.json
  config/util/representation-conversion/default.json
Labels: 🐛 bug, semver.patch

#1040 fix: Add webid claim to webid scope
  RELEASE_NOTES.md
  config/identity/handler/provider-factory/identity.json
  test/integration/Identity.test.ts
Labels: semver.major

#1032 Make UnionHandler tolerate handler failures
  .eslintrc.js
  src/http/output/error/ConvertingErrorHandler.ts
  src/http/output/error/SafeErrorHandler.ts
  src/index.ts
  src/util/PromiseUtil.ts
  src/util/errors/ErrorUtil.ts
  src/util/errors/HttpErrorUtil.ts
  src/util/handlers/HandlerUtil.ts
  src/util/handlers/ParallelHandler.ts
  src/util/handlers/UnionHandler.ts
  test/integration/Setup.test.ts
  test/unit/authentication/UnionCredentialsExtractor.test.ts
  test/unit/util/errors/ErrorUtil.test.ts
  test/unit/util/errors/HttpErrorUtil.test.ts
  test/unit/util/handlers/HandlerUtil.test.ts
  test/unit/util/handlers/UnionHandler.test.ts
Labels: 🐛 bug, semver.patch

#1067 refactor: Simplify promiseSome
  src/util/PromiseUtil.ts
Labels: semver.patch
