Repository CommunitySolidServer/CommunitySolidServer, pull requests merged in 2021-12, with the labels that each got.

#1083 Accept lowercase Authorization tokens
  src/authentication/BearerWebIdExtractor.ts
  src/authentication/DPoPWebIdExtractor.ts
  src/authentication/UnsecureWebIdExtractor.ts
  test/unit/authentication/BearerWebIdExtractor.test.ts
  test/unit/authentication/DPoPWebIdExtractor.test.ts
  test/unit/authentication/UnsecureWebIdExtractor.test.ts
Labels: 🐛 bug

#1054 feat: Move OIDC library behaviour to separate path
  RELEASE_NOTES.md
  config/http/handler/default.json
  config/http/handler/handlers/oidc.json
  config/identity/handler/default.json
  config/identity/handler/provider-factory/identity.json
  src/identity/IdentityProviderHttpHandler.ts
  src/identity/OidcHttpHandler.ts
  src/identity/configuration/IdentityProviderFactory.ts
  src/index.ts
  src/server/AuthorizingHttpHandler.ts
  src/server/OperationHttpHandler.ts
  test/integration/Identity.test.ts
  test/integration/config/server-without-auth.json
  test/unit/identity/IdentityProviderHttpHandler.test.ts
  test/unit/identity/OidcHttpHandler.test.ts
  test/unit/identity/configuration/IdentityProviderFactory.test.ts
Labels: semver.patch

#1096 add: Add VoidLocker and unittest
  RELEASE_NOTES.md
  config/util/README.md
  config/util/resource-locker/debug-void.json
  src/index.ts
  src/util/locking/VoidLocker.ts
  test/unit/util/locking/VoidLocker.test.ts
Labels: semver.minor
