Repository CommunitySolidServer/CommunitySolidServer, pull requests merged in 2021-01, with the labels that each got.

#477 fix: Prevent POST requests from creating intermediate containers
  src/storage/DataAccessorBasedStore.ts
  test/unit/storage/DataAccessorBasedStore.test.ts
Labels: 🐛 bug

#479 Only convert representations when needed
  config/presets/representation-conversion.json
  src/index.ts
  src/storage/conversion/ContentTypeReplacer.ts
  test/unit/storage/conversion/ContentTypeReplacer.test.ts
  test/unit/storage/conversion/RdfToQuadConverter.test.ts
Labels: ☀️ enhancement

#475 fix: Don't get normalized metadata for root containers
  src/storage/DataAccessorBasedStore.ts
  test/unit/storage/DataAccessorBasedStore.test.ts
Labels: 🐛 bug

#490 Add transformSafely
  src/util/StreamUtil.ts
  test/unit/util/StreamUtil.test.ts
Labels: ➕ feature

#494 Use ldp: prefix in container representations
  src/storage/DataAccessorBasedStore.ts
  test/integration/LdpHandlerWithoutAuth.test.ts
Labels: ☀️ enhancement, 👩🏾‍💻 developer experience

#500 Allow Content-Type: 0 on GET
  src/ldp/http/RawBodyParser.ts
  test/integration/ServerWithAuth.test.ts
  test/unit/ldp/http/RawBodyParser.test.ts
Labels: 🐛 bug

#514 Eliminate repeated existence checks with containsResource function
  src/init/AclInitializer.ts
  src/init/RootContainerInitializer.ts
  src/pods/GeneratedPodManager.ts
  src/storage/StoreUtil.ts
  src/storage/routing/ConvertingRouterRule.ts
Labels: 📝 task

#523 test: cache moduleState in integration tests to reduce exec time
  test/integration/Config.ts
Labels: ☀️ enhancement

#503 Eliminate overlap between file mappers
  src/index.ts
  src/storage/mapping/BaseFileIdentifierMapper.ts
  src/storage/mapping/ExtensionBasedMapper.ts
  src/storage/mapping/FixedContentTypeMapper.ts
  src/util/PathUtil.ts
  test/unit/storage/mapping/BaseFileIdentifierMapper.test.ts
Labels: 📝 task

#532 Set the Vary header
  config/presets/middleware.json
  test/integration/Middleware.test.ts
Labels: 📝 task

#360 Test on Node 15
  .github/workflows/ci.yml
  package.json
Labels: ➕ test

#556 Only show coverage details with unit tests
  jest.config.js
  package.json
Labels: ➕ test

#559 Support folders in StaticAssetHandler
  package-lock.json
  package.json
  src/server/middleware/StaticAssetHandler.ts
  test/unit/server/middleware/StaticAssetHandler.test.ts
Labels: ➕ feature

#566 Do not re-encode static assets
  src/server/middleware/StaticAssetHandler.ts
  test/unit/server/middleware/StaticAssetHandler.test.ts
Labels: 🐛 bug
