Repository CommunitySolidServer/CommunitySolidServer, pull requests merged in 2021-09, with the labels that each got.

#925 feat: Allow filtering in ConstantConverter based on type
  src/storage/conversion/ConstantConverter.ts
  test/unit/storage/conversion/ConstantConverter.test.ts
Labels: semver.minor

#948 Rename resourceStore to aclStore
  config/ldp/authorization/authorizers/acl.json
  src/authorization/WebAclAuthorizer.ts
Labels: 👩🏾‍💻 developer experience

#936 refactor: Clean up internal storage
  config/identity/handler/account-store/default.json
  config/identity/handler/adapter-factory/webid.json
  config/identity/handler/default.json
  config/identity/handler/key-value/storage.json
  config/identity/handler/provider-factory/identity.json
  config/identity/ownership/token.json
  config/storage/key-value/memory.json
  config/storage/key-value/resource-store.json
  src/identity/configuration/IdentityProviderFactory.ts
  src/identity/interaction/email-password/storage/BaseAccountStore.ts
  src/identity/storage/ExpiringAdapterFactory.ts
  test/unit/identity/configuration/IdentityProviderFactory.test.ts
  test/unit/identity/interaction/email-password/storage/BaseAccountStore.test.ts
  test/unit/identity/storage/ExpiringAdapterFactory.test.ts
Labels: semver.major

#945 fix: Prevent parent containers from storing generated metadata
  src/storage/DataAccessorBasedStore.ts
  test/unit/storage/DataAccessorBasedStore.test.ts
Labels: semver.patch
