Repository CommunitySolidServer/CommunitySolidServer, pull requests merged in 2022-04, with the labels that each got.

#1252 Refactor: use fs-extra instead of fs to simplify file access
  src/storage/accessors/AtomicFileDataAccessor.ts
  src/storage/accessors/FileDataAccessor.ts
  src/storage/keyvalue/JsonFileStorage.ts
  test/unit/pods/generate/TemplatedResourcesGenerator.test.ts
  test/unit/quota/PodQuotaStrategy.test.ts
  test/unit/quota/QuotaStrategy.test.ts
  test/unit/storage/accessors/AtomicFileDataAccessor.test.ts
  test/unit/storage/accessors/FileDataAccessor.test.ts
  test/unit/storage/keyvalue/JsonFileStorage.test.ts
  test/unit/storage/size-reporter/FileSizeReporter.test.ts
  test/unit/util/templates/TemplateEngine.test.ts
  test/util/Util.ts
Labels: semver.patch

#1260 feat: new helper functions to replace regexes #807
  src/authentication/BearerWebIdExtractor.ts
  src/authentication/DPoPWebIdExtractor.ts
  src/authentication/UnsecureWebIdExtractor.ts
  src/http/UnsecureWebSocketsProtocol.ts
  src/http/input/conditions/BasicConditionsParser.ts
  src/identity/interaction/email-password/util/RegistrationManager.ts
  src/identity/storage/WebIdAdapterFactory.ts
  src/index.ts
  src/pods/generate/SubdomainIdentifierGenerator.ts
  src/pods/generate/SuffixIdentifierGenerator.ts
  src/server/middleware/WebSocketAdvertiser.ts
  src/storage/IndexRepresentationStore.ts
  src/storage/conversion/ErrorToTemplateConverter.ts
  src/util/HeaderUtil.ts
  src/util/StringUtil.ts
  test/integration/Middleware.test.ts
  test/unit/util/HeaderUtil.test.ts
  test/unit/util/StringUtil.test.ts
Labels: semver.minor

#1258 feat: Add support for client_credentials authentication
  .eslintrc.js
  RELEASE_NOTES.md
  config/identity/handler/adapter-factory/webid.json
  config/identity/handler/interaction/routes.json
  config/identity/handler/interaction/routes/credentials.json
  config/identity/handler/interaction/views/controls.json
  config/identity/handler/provider-factory/identity.json
  documentation/README.md
  documentation/client-credentials.md
  documentation/idp.md
  package-lock.json
  package.json
  src/identity/configuration/IdentityProviderFactory.ts
  src/identity/interaction/ControlHandler.ts
  src/identity/interaction/email-password/credentials/ClientCredentialsAdapterFactory.ts
  src/identity/interaction/email-password/credentials/CreateCredentialsHandler.ts
  src/identity/interaction/email-password/credentials/CredentialsHandler.ts
  src/identity/interaction/email-password/credentials/DeleteCredentialsHandler.ts
  src/identity/interaction/email-password/credentials/EmailPasswordAuthorizer.ts
  src/identity/interaction/email-password/credentials/ListCredentialsHandler.ts
  src/identity/interaction/email-password/storage/AccountStore.ts
  src/identity/interaction/email-password/util/RegistrationManager.ts
  src/identity/storage/AdapterFactory.ts
  src/identity/storage/PassthroughAdapterFactory.ts
  src/identity/storage/WebIdAdapterFactory.ts
  src/index.ts
  test/integration/Identity.test.ts
  test/unit/authorization/OwnerPermissionReader.test.ts
  test/unit/identity/ControlHandler.test.ts
  test/unit/identity/configuration/IdentityProviderFactory.test.ts
  test/unit/identity/interaction/email-password/credentials/ClientCredentialsAdapterFactory.test.ts
  test/unit/identity/interaction/email-password/credentials/CreateCredentialsHandler.test.ts
  test/unit/identity/interaction/email-password/credentials/DeleteCredentialsHandler.test.ts
  test/unit/identity/interaction/email-password/credentials/EmailPasswordAuthorizer.test.ts
  test/unit/identity/interaction/email-password/credentials/ListCredentialsHandler.test.ts
  test/unit/identity/interaction/email-password/handler/LoginHandler.test.ts
  test/unit/identity/interaction/email-password/storage/BaseAccountStore.test.ts
  test/unit/identity/interaction/email-password/util/RegistrationManager.test.ts
  test/unit/identity/storage/PassthroughAdapterFactory.test.ts
  test/unit/identity/storage/WebIdAdapterFactory.test.ts
Labels: semver.major

#1265 fix: %2F not handled correctly in file backend #1184
  src/util/PathUtil.ts
  test/integration/FileBackendEncodedSlashHandling.test.ts
  test/integration/config/server-file.json
  test/unit/util/PathUtil.test.ts
  test/util/Util.ts
Labels: semver.patch

#1273 Make delimiter encoding case-insensitive
  src/util/PathUtil.ts
  test/integration/FileBackendEncodedSlashHandling.test.ts
  test/unit/util/PathUtil.test.ts
Labels: semver.patch

#1274 feat: add a process-/thread-safe file-based ResourceLocker
  RELEASE_NOTES.md
  config/example-https-file.json
  config/file-no-setup.json
  config/file.json
  config/https-file-cli.json
  config/quota-file.json
  config/restrict-idp.json
  config/sparql-file-storage.json
  config/util/README.md
  config/util/resource-locker/file.json
  config/util/resource-locker/memory.json
  package-lock.json
  package.json
  src/index.ts
  src/util/LockUtils.ts
  src/util/locking/FileSystemResourceLocker.ts
  src/util/locking/MemoryResourceLocker.ts
  src/util/locking/RedisLocker.ts
  src/util/locking/scripts/RedisLuaScripts.ts
  test/integration/LockingResourceStore.test.ts
  test/integration/RedisLocker.test.ts
  test/unit/util/LockUtil.test.ts
  test/unit/util/locking/FileSystemResourceLocker.test.ts
  test/unit/util/locking/MemoryResourceLocker.test.ts
Labels: semver.major
