Repository CommunitySolidServer/CommunitySolidServer, pull requests merged in 2022-09, with the labels that each got.

#1460 Put default consent button in expected position
  templates/identity/email-password/consent.html.ejs
  templates/scripts/util.js
  templates/styles/main.css
Labels: ☀️ enhancement

#1447 fix: Always render OIDC errors correctly
  src/identity/configuration/IdentityProviderFactory.ts
  test/integration/Identity.test.ts
  test/unit/identity/configuration/IdentityProviderFactory.test.ts
Labels: semver.patch

#1435 Allow multiple configurations to be used during startup
  README.md
  config/app/variables/cli/cli.json
  src/init/AppRunner.ts
  test/integration/Cli.test.ts
  test/unit/init/AppRunner.test.ts
Labels: semver.minor

#1437 feat: Allow JSON-LD contexts to be stored locally
  package-lock.json
  package.json
  src/storage/conversion/RdfToQuadConverter.ts
  test/assets/contexts/test.jsonld
  test/unit/storage/conversion/RdfToQuadConverter.test.ts
Labels: semver.minor
